from numpy.random import randint


def one_paire_crossover(parent1 : list[int], parent2 : list[int], cut_index : int) -> tuple[list[int], list[int]]:

    """
    Perform one-point crossover on two parent chromosomes.

    Args:
        parent1 (list[int]): First parent chromosome.
        parent2 (list[int]): Second parent chromosome.
        cut_index (int): Index at which to perform the crossover.

    Returns:
        tuple[list[int], list[int]]: Two child chromosomes generated by the crossover.
    """

    child1 = parent1.copy()
    child2 = parent2.copy()

    temp = child1[cut_index:].copy()

    child1[cut_index:] = child2[cut_index:]
    child2[cut_index:] = temp

    return child1, child2


def crossover(population : list[list[int]]) -> list[list[int]]:

    """
    Perform crossover on a population of chromosomes.

    Args:
        population (list[list[int]]): List of parent chromosomes.

    Returns:
        list[list[int]]: List of child chromosomes.
    """

    new_population = []

    for i in range(0, len(population), 2):
        cut_index = randint(1, len(population[i]))
        parent1, parent2 = one_paire_crossover(population[i], population[i + 1], cut_index)
        new_population.append(parent1)
        new_population.append(parent2)

    return new_population
